[package]
name = "vxapo-cli"
version = "0.3.2"
edition = "2021"
description = "VxAPO command-line tool for device management and diagnostics"
license = "GPL-3.0-or-later"

[dependencies]
winreg = "0.52"
vxapo-driver = { path = "../vxapo-driver" }
windows = { version = "0.62.2", features = [
  "Win32_System_Registry",
  "Win32_Foundation",
  "Win32_Media_Audio",
  "Win32_Media_Audio_Endpoints",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Ole",
] }
